version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      HTTP_SERVER_HOST: ${HTTP_SERVER_HOST}
      HTTP_SERVER_PORT: ${HTTP_SERVER_PORT}
      DB_DRIVER:        ${DB_DRIVER}
      DB_HOST:          ${DB_HOST}
      DB_PORT:          ${DB_PORT}
      DB_USER:          ${DB_USER}
      DB_PASSWORD:      ${DB_PASSWORD}
      DB_NAME:          ${DB_NAME}
    depends_on:
      - database

  database:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER:     ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB:       ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
